<?php

declare(strict_types=1);

namespace RockAdmin\Tests\Integration\Form;

use PHPUnit\Framework\Attributes\CoversNothing;
use PHPUnit\Framework\Attributes\DataProvider;
use RockAdmin\Config\Loader;
use RockAdmin\Db\Connection;
use RockAdmin\Db\Sql;
use RockAdmin\Db\SqlRowSource;
use RockAdmin\Db\SqlWriteHandler;
use RockAdmin\Form\FieldValidator;
use RockAdmin\Form\FormFields;
use RockAdmin\Form\FormRegion;
use RockAdmin\Http\ActionHandler;
use RockAdmin\Http\ArraySessionStore;
use RockAdmin\Http\Csrf;
use RockAdmin\Http\FormHandler;
use RockAdmin\Http\Request;
use RockAdmin\Http\Response;
use RockAdmin\Http\Route;
use RockAdmin\Http\SessionStore;
use RockAdmin\Http\UrlGenerator;
use RockAdmin\Page\PageRepository;
use RockAdmin\Tests\Support\DatabaseTestCase;
use RockAdmin\View\Assets;
use RockAdmin\View\Escaper;
use RockAdmin\View\FlashBag;
use RockAdmin\View\Renderer;
use RockAdmin\View\TemplateResolver;

/**
 * The demo, driven from a test.
 *
 * Every other test in this milestone writes its own page file; this one reads
 * `demo/config/pages/ads.php` and `demo/config/enums.php` as they ship. That
 * is the whole point of it: the demo is the worked example the documentation
 * points at, and a worked example that stopped loading would be found by
 * whoever opened the demo next rather than by the build. The browser check in
 * task 9's report is what this file cannot do; this file is what keeps that
 * check from being the only thing standing behind the demo.
 *
 * `#[CoversNothing]` on purpose: it covers the demo's configuration, which is
 * not a class.
 *
 * **Fixtures.** This test writes, so it builds its own `ra_test_ads` in the
 * shape `demo/seed.php` creates -- a generated key and the four columns the
 * form needs -- and in `tearDown()` puts `DatabaseTestCase`'s own fixtures
 * back exactly as they were, for any test that runs after it. It does not
 * create its own uniquely named table the way `WriteTest` and `WriteFlowTest`
 * do, because the page under test names `ra_test_ads` in a file that ships,
 * and renaming the table would mean testing a copy of the configuration
 * rather than the configuration.
 */
#[CoversNothing]
final class DemoFormTest extends DatabaseTestCase
{
    private SessionStore $session;

    protected function setUp(): void
    {
        parent::setUp();

        $this->session = new ArraySessionStore();

        foreach (self::connections() as [$connection]) {
            if ($connection !== null) {
                $this->createDemoFixture($connection);
            }
        }
    }

    protected function tearDown(): void
    {
        foreach (self::connections() as [$connection]) {
            if ($connection !== null) {
                $this->createFixtures($connection);
            }
        }

        parent::tearDown();
    }

    /**
     * The demo's own table shape: `demo/seed.php`'s DDL, with the ads the
     * page's `form` block writes to and the users its `user` relation joins.
     */
    private function createDemoFixture(Connection $connection): void
    {
        $this->dropFixtures($connection);

        $mysql = $connection->dialect()->name() === 'mysql';
        $json = $mysql ? 'JSON' : 'JSONB';
        $key = $mysql
            ? 'INTEGER AUTO_INCREMENT PRIMARY KEY'
            : 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
        $boolean = $mysql ? 'TINYINT(1)' : 'BOOLEAN';
        $false = $mysql ? '0' : 'FALSE';

        $connection->execute(new Sql(
            'CREATE TABLE ra_test_users (id INTEGER PRIMARY KEY, company_id INTEGER, '
            . 'name VARCHAR(100) NOT NULL, email VARCHAR(100))',
        ));
        $connection->execute(new Sql(
            "CREATE TABLE ra_test_ads (id {$key}, user_id INTEGER, "
            . 'title VARCHAR(200) NOT NULL, description TEXT, price INTEGER, state VARCHAR(20), '
            . "featured {$boolean} NOT NULL DEFAULT {$false}, published_on DATE, stats {$json}, "
            . 'created_at TIMESTAMP)',
        ));
        $connection->execute(new Sql(
            'INSERT INTO ra_test_users (id, company_id, name, email) VALUES (?, ?, ?, ?)',
            [1, 1, 'Jana', 'jana@example.com'],
        ));
    }

    /** The demo's configuration, read from the files the demo ships. */
    private function repository(): PageRepository
    {
        $root = \dirname(__DIR__, 3) . '/demo/config';
        $env = static fn (string $name): ?string => null;
        $config = (new Loader($root, $env))->load();

        return new PageRepository($root . '/pages', $env, $config->enums());
    }

    private function urls(): UrlGenerator
    {
        return new UrlGenerator('/');
    }

    private function forms(Connection $connection): FormHandler
    {
        $urls = $this->urls();

        return new FormHandler(
            $this->repository(),
            new FormRegion(new SqlRowSource($connection), $urls, new Csrf($this->session)),
            new Renderer(new TemplateResolver([]), new Escaper(), $urls),
            new Assets($urls),
            new FlashBag($this->session),
            $urls,
            'RockAdmin Demo',
            'auto',
        );
    }

    private function actions(Connection $connection): ActionHandler
    {
        $urls = $this->urls();
        $csrf = new Csrf($this->session);

        return new ActionHandler(
            $this->repository(),
            new FormRegion(new SqlRowSource($connection), $urls, $csrf),
            new FieldValidator(),
            new SqlWriteHandler($connection),
            $this->forms($connection),
            $csrf,
            new FlashBag($this->session),
            $urls,
        );
    }

    private function get(Connection $connection, string $route, string $id = '', string $returnTo = ''): Response
    {
        $params = ['page' => 'ads'];

        if ($id !== '') {
            $params['id'] = $id;
        }

        $query = $returnTo === '' ? [] : [FormFields::RETURN_TO => $returnTo];

        return $this->forms($connection)->handle(
            new Route($route, $params),
            new Request('GET', 'p/ads', $query),
        );
    }

    /** @param array<string, mixed> $body */
    private function post(Connection $connection, string $action, array $body): Response
    {
        return $this->actions($connection)->handle(
            new Route('action', ['page' => 'ads', 'action' => $action]),
            new Request(
                'POST',
                "a/ads/{$action}",
                body: [Csrf::FIELD => (new Csrf($this->session))->token()] + $body,
            ),
        );
    }

    /** @return list<array<string, mixed>> read with plain SQL, never through the classes under test */
    private function ads(Connection $connection): array
    {
        return $connection->select(new Sql('SELECT * FROM ra_test_ads ORDER BY id'));
    }

    private function scalarValue(mixed $value): string
    {
        if (!\is_scalar($value)) {
            $this->fail('Expected a scalar, got ' . get_debug_type($value));
        }

        return (string) $value;
    }

    /** PostgreSQL returns a BOOLEAN as 't'/'f'; MySQL returns TINYINT(1) as 0/1. */
    private function boolValue(mixed $value): bool
    {
        if (\is_bool($value)) {
            return $value;
        }

        return \in_array($value, [1, '1', 't', 'true'], true);
    }

    /** @return array<string, mixed> the values a valid create posts */
    private function validBody(): array
    {
        return [
            'title' => 'Nákladní kolo Bullitt',
            'description' => 'Cargo bike, two seats.',
            'price' => '18500',
            'state' => 'active',
            'featured' => '1',
            'published_on' => '2026-09-30',
        ];
    }

    #[DataProvider('connections')]
    public function testTheDemosOwnConfigurationLoadsAndDeclaresAForm(?Connection $connection): void
    {
        $this->requireConnection($connection);

        $page = $this->repository()->get('ads');
        $region = $page->firstFormRegion();

        $this->assertNotNull($region, 'the demo ads page is expected to declare a form region');
        $form = $region->form;
        $this->assertNotNull($form);

        $this->assertSame(
            ['title', 'description', 'price', 'state', 'featured', 'published_on', 'created_at'],
            array_keys($form->fields),
        );
        $this->assertSame(['published_on'], $form->resetOnCopy);

        // A hidden field is never editable, which is what stops a submission
        // setting created_at from the wire.
        $this->assertArrayNotHasKey('created_at', $form->editable());

        // The select's options come from demo/config/enums.php, through the
        // same @enum: reference the grid's badge and filter read.
        $this->assertSame(['active', 'draft', 'sold'], array_keys($form->field('state')->options));
    }

    #[DataProvider('connections')]
    public function testACreateFormDrawsTheDeclaredDefaults(?Connection $connection): void
    {
        $connection = $this->requireConnection($connection);

        $body = $this->get($connection, 'page.create')->body;

        $this->assertStringContainsString('value="5000"', $body, 'price declares default 5000');
        $this->assertStringContainsString('<option value="draft" selected>Draft</option>', $body);
        $this->assertStringContainsString(
            'value="' . date('Y-m-d') . '"',
            $body,
            'published_on declares @now, which for a date field is today',
        );

        // The hidden field's default is applied on save, never put in the
        // page: a value in the document is a value somebody can edit.
        $this->assertStringNotContainsString('name="created_at"', $body);
    }

    #[DataProvider('connections')]
    public function testCreatingThroughTheActionRouteStoresTheRowAndFlashes(?Connection $connection): void
    {
        $connection = $this->requireConnection($connection);

        $response = $this->post($connection, 'create', $this->validBody());

        $this->assertSame(302, $response->status);
        $this->assertSame('/p/ads', $response->headers['location']);

        $rows = $this->ads($connection);
        $this->assertCount(1, $rows);
        $this->assertSame('Nákladní kolo Bullitt', $rows[0]['title']);
        $this->assertSame('Cargo bike, two seats.', $rows[0]['description']);
        $this->assertSame(18500, (int) $this->scalarValue($rows[0]['price']));
        $this->assertSame('active', $rows[0]['state']);
        $this->assertTrue($this->boolValue($rows[0]['featured']));
        $this->assertNotSame('', $this->scalarValue($rows[0]['id']), 'the database assigns the key');

        $flashes = (new FlashBag($this->session))->take();
        $this->assertCount(1, $flashes);
        $this->assertSame('success', $flashes[0]->level);
    }

    /**
     * The hidden `created_at` carries `@now`, and spec 7.6's "a default
     * applies again on save" is restricted to a create. If it applied on an
     * update too, every typo fix would restamp the row's own creation time.
     */
    #[DataProvider('connections')]
    public function testTheHiddenDefaultIsStampedOnCreateAndLeftAloneOnUpdate(?Connection $connection): void
    {
        $connection = $this->requireConnection($connection);

        $this->post($connection, 'create', $this->validBody());
        $row = $this->ads($connection)[0];
        $key = $this->scalarValue($row['id']);
        $stamped = $this->scalarValue($row['created_at']);

        $this->assertNotSame('', $stamped, '@now is applied on save for a field the form never offered');

        $this->post($connection, 'update', [FormFields::ID => $key] + $this->validBody() + ['title' => 'Renamed']);

        $this->assertSame($stamped, $this->scalarValue($this->ads($connection)[0]['created_at']));
    }

    #[DataProvider('connections')]
    public function testSavingAnEditReturnsToTheGridPageItCameFrom(?Connection $connection): void
    {
        $connection = $this->requireConnection($connection);

        $this->post($connection, 'create', $this->validBody());
        $key = $this->scalarValue($this->ads($connection)[0]['id']);
        $returnTo = '/p/ads?grid%5Bf%5D%5Bstate%5D=active&grid%5Bpage%5D=2';

        $form = $this->get($connection, 'page.edit', $key, $returnTo)->body;
        $this->assertStringContainsString('value="Nákladní kolo Bullitt"', $form);
        // The value is escaped into the attribute, `&` and all: this asserts
        // the markup a browser actually receives rather than the raw string.
        $this->assertStringContainsString(
            'name="' . FormFields::RETURN_TO . '" value="' . htmlspecialchars($returnTo, ENT_QUOTES) . '"',
            $form,
        );

        $response = $this->post($connection, 'update', [
            FormFields::ID => $key,
            FormFields::RETURN_TO => $returnTo,
        ] + $this->validBody());

        $this->assertSame(302, $response->status);
        $this->assertSame($returnTo, $response->headers['location'], 'the filters must survive the save');
    }

    #[DataProvider('connections')]
    public function testAnInvalidSubmissionComesBackAt422AndWritesNothing(?Connection $connection): void
    {
        $connection = $this->requireConnection($connection);

        $response = $this->post($connection, 'create', [
            'title' => 'ab',
            'price' => 'not a number',
            'state' => 'nonsense',
        ]);

        $this->assertSame(422, $response->status);
        $this->assertStringContainsString('value="ab"', $response->body, 'what was typed must still be there');
        $this->assertStringContainsString('value="not a number"', $response->body);
        $this->assertStringContainsString('ra-form-errors', $response->body, 'the summary at the top');
        $this->assertStringContainsString('ra-form-error', $response->body, 'and the error against the field');
        $this->assertSame([], $this->ads($connection), 'a refused submission writes nothing');

        // Every failure at once, not just the first: three fields were wrong.
        $this->assertSame(3, substr_count($response->body, 'class="ra-form-error"'));
    }

    #[DataProvider('connections')]
    public function testACopyCarriesEverythingExceptTheFieldCopyResetNames(?Connection $connection): void
    {
        $connection = $this->requireConnection($connection);

        $this->post($connection, 'create', ['published_on' => '2001-02-03'] + $this->validBody());
        $key = $this->scalarValue($this->ads($connection)[0]['id']);

        $body = $this->get($connection, 'page.copy', $key)->body;

        $this->assertStringContainsString('value="Nákladní kolo Bullitt"', $body, 'the title is carried');
        $this->assertStringContainsString('value="18500"', $body, 'the price is carried');
        $this->assertStringContainsString('<option value="active" selected>Active</option>', $body);
        $this->assertStringContainsString(
            'value="' . date('Y-m-d') . '"',
            $body,
            'published_on is in copy.reset, so it starts at its @now default again',
        );
        $this->assertStringNotContainsString('value="2001-02-03"', $body);

        // A copy is a create: it posts to the create action and names no row.
        $this->assertStringContainsString('action="/a/ads/create"', $body);
        $this->assertStringNotContainsString('name="' . FormFields::ID . '"', $body);
    }

    #[DataProvider('connections')]
    public function testADeleteRemovesTheRowAndFlashes(?Connection $connection): void
    {
        $connection = $this->requireConnection($connection);

        $this->post($connection, 'create', $this->validBody());
        $key = $this->scalarValue($this->ads($connection)[0]['id']);

        // The edit form is where the Delete button lives, and it is a submit
        // button of that same form redirected with `formaction`.
        $form = $this->get($connection, 'page.edit', $key)->body;
        $this->assertStringContainsString('formaction="/a/ads/delete"', $form);
        $this->assertStringContainsString('data-ra-confirm', $form);

        (new FlashBag($this->session))->take();

        $response = $this->post($connection, 'delete', [FormFields::ID => $key]);

        $this->assertSame(302, $response->status);
        $this->assertSame([], $this->ads($connection));

        $flashes = (new FlashBag($this->session))->take();
        $this->assertCount(1, $flashes);
        $this->assertStringContainsString('Deleted', $flashes[0]->message);
    }
}
