<?php

declare(strict_types=1);

namespace RockAdmin\Tests\Integration\Form;

use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\DataProvider;
use RockAdmin\Config\Enums;
use RockAdmin\Db\Connection;
use RockAdmin\Db\Sql;
use RockAdmin\Db\SqlRowSource;
use RockAdmin\Db\SqlWriteHandler;
use RockAdmin\Form\FieldValidator;
use RockAdmin\Form\FormFields;
use RockAdmin\Form\FormRegion;
use RockAdmin\Http\ActionHandler;
use RockAdmin\Http\ArraySessionStore;
use RockAdmin\Http\Csrf;
use RockAdmin\Http\FormHandler;
use RockAdmin\Http\Request;
use RockAdmin\Http\Response;
use RockAdmin\Http\Route;
use RockAdmin\Http\SessionStore;
use RockAdmin\Http\UrlGenerator;
use RockAdmin\Page\PageRepository;
use RockAdmin\Tests\Support\DatabaseTestCase;
use RockAdmin\View\Assets;
use RockAdmin\View\Escaper;
use RockAdmin\View\FlashBag;
use RockAdmin\View\Renderer;
use RockAdmin\View\TemplateResolver;

/**
 * The whole write path, end to end, on every configured server: a page
 * described in a file, a POST to the action route, a real `SqlWriteHandler`
 * over a real connection, and the row read back with plain SQL rather than
 * through any of the classes under test.
 *
 * Like `tests/Integration/Db/WriteTest.php`, this creates its own table
 * (`ra_test_flow`) in `setUp()` and drops it in `tearDown()`, on every
 * configured connection, rather than writing to `DatabaseTestCase`'s shared
 * read-only fixtures. A failing assertion here must not leave `ra_test_ads`
 * wrong for a test that runs after it.
 *
 * `id` is a generated `BIGINT` — `AUTO_INCREMENT` on MySQL, `GENERATED BY
 * DEFAULT AS IDENTITY` on PostgreSQL — because that is what a real table's
 * key looks like, and a narrower fixture with a key the test supplied itself
 * is what hid a defect earlier in this milestone. `active` is a boolean
 * column behind a checkbox field, because storing `false` at all was broken
 * until two days ago: PDO binds an array of values as strings and PHP
 * stringifies `false` to `''`.
 */
#[CoversClass(ActionHandler::class)]
#[CoversClass(FormHandler::class)]
final class WriteFlowTest extends DatabaseTestCase
{
    private string $root;

    private SessionStore $session;

    protected function setUp(): void
    {
        parent::setUp();

        $this->root = str_replace('\\', '/', sys_get_temp_dir()) . '/ra-write-flow-' . bin2hex(random_bytes(6));
        mkdir($this->root . '/pages', 0o777, true);
        $this->writePage();

        $this->session = new ArraySessionStore();

        foreach (self::connections() as [$connection]) {
            if ($connection !== null) {
                $this->createFlowFixture($connection);
            }
        }
    }

    protected function tearDown(): void
    {
        foreach (self::connections() as [$connection]) {
            if ($connection !== null) {
                $connection->execute(new Sql('DROP TABLE IF EXISTS ra_test_flow'));
            }
        }

        $this->remove($this->root);

        parent::tearDown();
    }

    private function remove(string $path): void
    {
        if (is_file($path)) {
            unlink($path);

            return;
        }

        if (!is_dir($path)) {
            return;
        }

        foreach (array_diff(scandir($path) ?: [], ['.', '..']) as $entry) {
            $this->remove($path . '/' . $entry);
        }

        rmdir($path);
    }

    private function createFlowFixture(Connection $connection): void
    {
        $connection->execute(new Sql('DROP TABLE IF EXISTS ra_test_flow'));

        [$key, $active] = $connection->dialect()->name() === 'mysql'
            ? ['BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY', 'TINYINT(1) NOT NULL DEFAULT 1']
            : ['BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', 'BOOLEAN NOT NULL DEFAULT TRUE'];

        $connection->execute(new Sql(
            "CREATE TABLE ra_test_flow (id {$key}, title VARCHAR(100) NOT NULL UNIQUE, "
                . "price INTEGER, active {$active})",
        ));
    }

    private function writePage(): void
    {
        file_put_contents($this->root . '/pages/flow.php', <<<'PHP'
            <?php

            return [
                'title' => 'Flow',
                'entity' => ['table' => 'ra_test_flow'],
                'regions' => [
                    'grid' => ['type' => 'list', 'columns' => ['title' => []]],
                    'form' => [
                        'type' => 'form',
                        'form' => [
                            'fields' => [
                                'title' => ['type' => 'text', 'required' => true],
                                'price' => ['type' => 'number'],
                                'active' => ['type' => 'checkbox'],
                            ],
                        ],
                    ],
                ],
            ];
            PHP);
    }

    private function repository(): PageRepository
    {
        return new PageRepository(
            $this->root . '/pages',
            static fn (string $name): ?string => null,
            Enums::fromConfig([]),
        );
    }

    private function actions(Connection $connection): ActionHandler
    {
        $urls = new UrlGenerator('/admin');
        $csrf = new Csrf($this->session);
        $flashes = new FlashBag($this->session);
        $region = new FormRegion(new SqlRowSource($connection), $urls, $csrf);
        $renderer = new Renderer(new TemplateResolver([]), new Escaper(), $urls);

        return new ActionHandler(
            $this->repository(),
            $region,
            new FieldValidator(),
            new SqlWriteHandler($connection),
            new FormHandler(
                $this->repository(),
                $region,
                $renderer,
                new Assets($urls),
                $flashes,
                $urls,
                'RockAdmin',
                'auto',
            ),
            $csrf,
            $flashes,
            $urls,
        );
    }

    /**
     * @param  array<string, mixed> $body
     */
    private function post(Connection $connection, string $action, array $body): Response
    {
        return $this->actions($connection)->handle(
            new Route('action', ['page' => 'flow', 'action' => $action]),
            new Request(
                'POST',
                "a/flow/{$action}",
                body: [Csrf::FIELD => (new Csrf($this->session))->token()] + $body,
            ),
        );
    }

    /** @return list<array<string, mixed>> read with plain SQL, never through the classes under test */
    private function rows(Connection $connection): array
    {
        return $connection->select(new Sql('SELECT * FROM ra_test_flow ORDER BY id'));
    }

    /** Both drivers may hand an integer column back as a numeric string. */
    private function intValue(mixed $value): int
    {
        if (!\is_scalar($value)) {
            $this->fail('Expected a scalar, got ' . get_debug_type($value));
        }

        return (int) $value;
    }

    /** A generated BIGINT key comes back as an int or a string, driver depending. */
    private function stringValue(mixed $value): string
    {
        if (!\is_scalar($value)) {
            $this->fail('Expected a scalar, got ' . get_debug_type($value));
        }

        return (string) $value;
    }

    /** PostgreSQL returns a BOOLEAN as 't'/'f'; MySQL returns TINYINT(1) as 0/1. */
    private function boolValue(mixed $value): bool
    {
        if (\is_bool($value)) {
            return $value;
        }

        if ($value === 1 || $value === '1' || $value === 't' || $value === 'true') {
            return true;
        }

        if ($value === 0 || $value === '0' || $value === 'f' || $value === 'false') {
            return false;
        }

        $this->fail('Expected a boolean-ish value, got ' . get_debug_type($value));
    }

    #[DataProvider('connections')]
    public function testACreateThroughTheActionRouteStoresTheRow(?Connection $connection): void
    {
        $connection = $this->requireConnection($connection);

        $response = $this->post($connection, 'create', [
            'title' => 'Horské kolo',
            'price' => '12000',
            'active' => '1',
        ]);

        $this->assertSame(302, $response->status);
        $this->assertSame('/admin/p/flow', $response->headers['location']);

        $rows = $this->rows($connection);
        $this->assertCount(1, $rows);
        $this->assertSame('Horské kolo', $rows[0]['title']);
        $this->assertSame(12000, $this->intValue($rows[0]['price']));
        $this->assertTrue($this->boolValue($rows[0]['active']));
        $this->assertNotSame('', $this->stringValue($rows[0]['id']), 'the database was expected to assign a key');
    }

    /**
     * An unticked checkbox sends nothing at all, and "nothing" there means
     * `false` rather than "leave it alone". The column defaults to TRUE, so a
     * write that dropped the value would read back as true and this assertion
     * is the only thing that can tell the two apart.
     */
    #[DataProvider('connections')]
    public function testAnUntickedCheckboxStoresFalseRatherThanTheColumnsDefault(?Connection $connection): void
    {
        $connection = $this->requireConnection($connection);

        $this->post($connection, 'create', ['title' => 'Horské kolo', 'price' => '12000']);

        $rows = $this->rows($connection);
        $this->assertCount(1, $rows);
        $this->assertFalse($this->boolValue($rows[0]['active']));
    }

    #[DataProvider('connections')]
    public function testAnEditThroughTheActionRouteChangesTheStoredRow(?Connection $connection): void
    {
        $connection = $this->requireConnection($connection);

        $this->post($connection, 'create', ['title' => 'Horské kolo', 'price' => '12000', 'active' => '1']);
        $key = $this->stringValue($this->rows($connection)[0]['id']);

        $response = $this->post($connection, 'update', [
            FormFields::ID => $key,
            'title' => 'Silniční kolo',
            'price' => '25000',
            'active' => '1',
        ]);

        $this->assertSame(302, $response->status);

        $rows = $this->rows($connection);
        $this->assertCount(1, $rows);
        $this->assertSame('Silniční kolo', $rows[0]['title']);
        $this->assertSame(25000, $this->intValue($rows[0]['price']));
    }

    #[DataProvider('connections')]
    public function testAnEditFormDrawsTheStoredValuesBack(?Connection $connection): void
    {
        $connection = $this->requireConnection($connection);

        $this->post($connection, 'create', ['title' => 'Horské kolo', 'price' => '12000', 'active' => '1']);
        $key = $this->stringValue($this->rows($connection)[0]['id']);

        $urls = new UrlGenerator('/admin');
        $csrf = new Csrf($this->session);
        $forms = new FormHandler(
            $this->repository(),
            new FormRegion(new SqlRowSource($connection), $urls, $csrf),
            new Renderer(new TemplateResolver([]), new Escaper(), $urls),
            new Assets($urls),
            new FlashBag($this->session),
            $urls,
            'RockAdmin',
            'auto',
        );

        $response = $forms->handle(
            new Route('page.edit', ['page' => 'flow', 'id' => $key]),
            new Request('GET', "p/flow/{$key}/edit"),
        );

        $this->assertSame(200, $response->status);
        $this->assertStringContainsString('value="Horské kolo"', $response->body);
        $this->assertStringContainsString('value="12000"', $response->body);
        $this->assertStringContainsString('name="' . FormFields::ID . '" value="' . $key . '"', $response->body);
    }

    #[DataProvider('connections')]
    public function testAnInvalidSubmissionComesBackAt422StillCarryingWhatWasTyped(?Connection $connection): void
    {
        $connection = $this->requireConnection($connection);

        $response = $this->post($connection, 'create', ['title' => '', 'price' => 'not a number']);

        $this->assertSame(422, $response->status);
        $this->assertStringContainsString('value="not a number"', $response->body);
        $this->assertSame([], $this->rows($connection), 'nothing may be written by a refused submission');
    }

    /**
     * `title` is UNIQUE, so the second insert is refused by the database
     * rather than by the form definition — SQLSTATE class 23 — and must come
     * back as a form error with the row count unchanged. This is the "a
     * failed write leaves nothing behind" case: on PostgreSQL the failed
     * statement also poisons the transaction, so a handler that caught the
     * error inside it would leave this connection unusable for every
     * assertion below.
     */
    #[DataProvider('connections')]
    public function testAWriteTheDatabaseRefusesLeavesNothingBehind(?Connection $connection): void
    {
        $connection = $this->requireConnection($connection);

        $this->post($connection, 'create', ['title' => 'Horské kolo', 'price' => '12000', 'active' => '1']);

        $response = $this->post($connection, 'create', ['title' => 'Horské kolo', 'price' => '999', 'active' => '1']);

        $this->assertSame(422, $response->status);
        $this->assertStringContainsString('ra-form-errors', $response->body);
        $this->assertCount(1, $this->rows($connection), 'the refused insert must have left nothing behind');
        $this->assertSame(12000, $this->intValue($this->rows($connection)[0]['price']));
    }

    #[DataProvider('connections')]
    public function testADeleteThroughTheActionRouteRemovesTheRow(?Connection $connection): void
    {
        $connection = $this->requireConnection($connection);

        $this->post($connection, 'create', ['title' => 'Horské kolo', 'price' => '12000', 'active' => '1']);
        $key = $this->stringValue($this->rows($connection)[0]['id']);

        $response = $this->post($connection, 'delete', [FormFields::ID => $key]);

        $this->assertSame(302, $response->status);
        $this->assertSame([], $this->rows($connection));
    }
}
