<?php

declare(strict_types=1);

namespace RockAdmin\Tests\Integration\Db;

use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\DataProvider;
use RockAdmin\Db\Connection;
use RockAdmin\Db\DbException;
use RockAdmin\Db\Entity;
use RockAdmin\Db\Sql;
use RockAdmin\Db\SqlWriteHandler;
use RockAdmin\Db\WriteHandler;
use RockAdmin\Tests\Support\DatabaseTestCase;
use RuntimeException;

/**
 * This is the first test in the project to mutate the database, so it does
 * not touch `ra_test_ads` and the rest of `DatabaseTestCase`'s shared
 * fixtures -- those are read-only everywhere else in the suite. Instead it
 * creates its own table, `ra_test_write`, before each test and drops it
 * after, on every configured connection, regardless of which one that test
 * happens to run against. The next mutating test in this project should do
 * the same rather than writing to the shared fixtures: a failing assertion
 * here must never leave `ra_test_ads` or its siblings wrong for a test that
 * runs after it.
 */
#[CoversClass(SqlWriteHandler::class)]
#[CoversClass(Connection::class)]
final class WriteTest extends DatabaseTestCase
{
    protected function setUp(): void
    {
        parent::setUp();

        foreach (self::connections() as [$connection]) {
            if ($connection !== null) {
                $this->createWriteFixture($connection);
            }
        }
    }

    protected function tearDown(): void
    {
        foreach (self::connections() as [$connection]) {
            if ($connection !== null) {
                $this->dropWriteFixture($connection);
            }
        }

        parent::tearDown();
    }

    /**
     * `id` is declared so the database can assign it, not so it must --
     * MySQL's `AUTO_INCREMENT` and PostgreSQL's `GENERATED BY DEFAULT AS
     * IDENTITY` (unlike `GENERATED ALWAYS`) both still accept an explicit
     * value, which is what lets the same table serve every insert test
     * below: the ones that give a key and the ones that let the database
     * assign one.
     *
     * `id` is `BIGINT` rather than `INTEGER` because the database this
     * admin actually runs against declares every key that way
     * (`bigint unsigned auto_increment` on MySQL) -- a `bigint` past
     * `PHP_INT_MAX` comes back from either driver as a string, not an int,
     * which `WriteHandler` already has to cope with via `stringKey()`.
     *
     * `active` is a boolean column, for the tests that store `false`
     * through it -- the one value that a naive `PDOStatement::execute()`
     * silently turns into `''` before it ever reaches the driver.
     */
    private function createWriteFixture(Connection $connection): void
    {
        $this->dropWriteFixture($connection);

        [$key, $active] = $connection->dialect()->name() === 'mysql'
            ? ['BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY', 'TINYINT(1) NOT NULL DEFAULT 1']
            : ['BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', 'BOOLEAN NOT NULL DEFAULT TRUE'];

        $connection->execute(new Sql(
            "CREATE TABLE ra_test_write (id {$key}, title VARCHAR(100) NOT NULL UNIQUE, "
                . "price INTEGER, active {$active})",
        ));
    }

    private function dropWriteFixture(Connection $connection): void
    {
        $connection->execute(new Sql('DROP TABLE IF EXISTS ra_test_write'));
    }

    private function entity(): Entity
    {
        return new Entity('ra_test_write', 'id');
    }

    private function handler(Connection $connection): WriteHandler
    {
        return new SqlWriteHandler($connection);
    }

    /** Both drivers may hand back an integer column as a numeric string. */
    private function intValue(mixed $value): int
    {
        if (!\is_scalar($value)) {
            $this->fail('Expected a scalar, got ' . get_debug_type($value));
        }

        return (int) $value;
    }

    /**
     * PostgreSQL's own driver hands a `BOOLEAN` column back as the string
     * `'t'` or `'f'`, not a PHP bool; MySQL's `TINYINT(1)` comes back as an
     * int or a numeric string depending on the driver's own settings. This
     * normalises whichever of those a test happens to read.
     */
    private function boolValue(mixed $value): bool
    {
        if (\is_bool($value)) {
            return $value;
        }

        if (\is_int($value)) {
            return $value !== 0;
        }

        if (\is_string($value)) {
            return \in_array(strtolower($value), ['1', 't', 'true'], true);
        }

        $this->fail('Expected a boolean-ish value, got ' . get_debug_type($value));
    }

    #[DataProvider('connections')]
    public function testAnInsertReturnsTheNewRowsKey(?Connection $connection): void
    {
        $connection = $this->requireConnection($connection);

        $result = $this->handler($connection)->insert(
            $this->entity(),
            ['id' => 1, 'title' => 'Horské kolo', 'price' => 12000],
        );

        $this->assertSame('1', $result->key);
    }

    #[DataProvider('connections')]
    public function testAnInsertWithNoKeyReturnsTheKeyTheDatabaseAssigned(?Connection $connection): void
    {
        $connection = $this->requireConnection($connection);

        $result = $this->handler($connection)->insert(
            $this->entity(),
            ['title' => 'Horské kolo', 'price' => 12000],
        );

        $this->assertNotSame('', $result->key, 'the database was expected to assign a key');
        $this->assertSame('Horské kolo', $result->after['title']);
    }

    #[DataProvider('connections')]
    public function testTwoInsertsWithNoKeyReturnDifferentKeys(?Connection $connection): void
    {
        $connection = $this->requireConnection($connection);
        $handler = $this->handler($connection);
        $entity = $this->entity();

        $first = $handler->insert($entity, ['title' => 'Horské kolo', 'price' => 12000]);
        $second = $handler->insert($entity, ['title' => 'Silniční kolo', 'price' => 25000]);

        $this->assertNotSame($first->key, $second->key);
    }

    /**
     * I2: a hidden key field on a create form has nothing to offer and
     * sends `''`, not an absent key -- that must still let the database
     * assign one, the same as leaving the field out entirely.
     */
    #[DataProvider('connections')]
    public function testAnInsertWithAnEmptyStringKeyLetsTheDatabaseAssignOne(?Connection $connection): void
    {
        $connection = $this->requireConnection($connection);

        $result = $this->handler($connection)->insert(
            $this->entity(),
            ['id' => '', 'title' => 'Horské kolo', 'price' => 12000],
        );

        $this->assertNotSame('', $result->key);
    }

    /**
     * C1: `PDOStatement::execute(array)` binds every value as
     * `PDO::PARAM_STR`, and PHP stringifies `false` to `''` before it ever
     * reaches PDO -- a value that MySQL refuses under
     * `STRICT_TRANS_TABLES` and PostgreSQL refuses unconditionally.
     * `Connection::run()` must bind `false` as `PDO::PARAM_BOOL` instead.
     */
    #[DataProvider('connections')]
    public function testABooleanFalseValueIsStoredAndReadBackAsFalse(?Connection $connection): void
    {
        $connection = $this->requireConnection($connection);

        $result = $this->handler($connection)->insert(
            $this->entity(),
            ['id' => 1, 'title' => 'Horské kolo', 'price' => 12000, 'active' => false],
        );

        $this->assertFalse($this->boolValue($result->after['active']));
    }

    #[DataProvider('connections')]
    public function testABooleanTrueValueIsStoredAndReadBackAsTrue(?Connection $connection): void
    {
        $connection = $this->requireConnection($connection);

        $result = $this->handler($connection)->insert(
            $this->entity(),
            ['id' => 1, 'title' => 'Horské kolo', 'price' => 12000, 'active' => true],
        );

        $this->assertTrue($this->boolValue($result->after['active']));
    }

    #[DataProvider('connections')]
    public function testAnUpdateCanStoreABooleanFalseValueToo(?Connection $connection): void
    {
        $connection = $this->requireConnection($connection);
        $handler = $this->handler($connection);
        $entity = $this->entity();

        $handler->insert($entity, ['id' => 1, 'title' => 'Horské kolo', 'price' => 12000, 'active' => true]);
        $result = $handler->update($entity, '1', ['active' => false]);

        $this->assertFalse($this->boolValue($result->after['active']));
    }

    #[DataProvider('connections')]
    public function testAnInsertedRowIsReadBackWithTheValuesGiven(?Connection $connection): void
    {
        $connection = $this->requireConnection($connection);

        $result = $this->handler($connection)->insert(
            $this->entity(),
            ['id' => 1, 'title' => 'Horské kolo', 'price' => 12000],
        );

        $this->assertSame([], $result->before);
        $this->assertSame('Horské kolo', $result->after['title']);
        $this->assertSame(12000, $this->intValue($result->after['price']));
    }

    #[DataProvider('connections')]
    public function testAnUpdateChangesOnlyTheColumnsGiven(?Connection $connection): void
    {
        $connection = $this->requireConnection($connection);
        $handler = $this->handler($connection);
        $entity = $this->entity();

        $handler->insert($entity, ['id' => 1, 'title' => 'Horské kolo', 'price' => 12000]);

        $result = $handler->update($entity, '1', ['price' => 15000]);

        $this->assertSame('Horské kolo', $result->after['title'], 'title was not part of the update');
        $this->assertSame(15000, $this->intValue($result->after['price']));
    }

    #[DataProvider('connections')]
    public function testAnUpdateReportsWhatActuallyChanged(?Connection $connection): void
    {
        $connection = $this->requireConnection($connection);
        $handler = $this->handler($connection);
        $entity = $this->entity();

        $handler->insert($entity, ['id' => 1, 'title' => 'Horské kolo', 'price' => 12000]);

        $result = $handler->update($entity, '1', ['title' => 'Horské kolo', 'price' => 15000]);

        $changed = $result->changed();

        $this->assertArrayNotHasKey('title', $changed, 'title was submitted unchanged');
        $this->assertArrayHasKey('price', $changed);
        $this->assertSame(15000, $this->intValue($changed['price'][1]));
    }

    #[DataProvider('connections')]
    public function testAnUpdateThatChangesNothingReportsNothing(?Connection $connection): void
    {
        $connection = $this->requireConnection($connection);
        $handler = $this->handler($connection);
        $entity = $this->entity();

        $handler->insert($entity, ['id' => 1, 'title' => 'Horské kolo', 'price' => 12000]);

        $result = $handler->update($entity, '1', ['title' => 'Horské kolo', 'price' => 12000]);

        $this->assertSame([], $result->changed());
    }

    /**
     * C2: an editable natural key (`code`, `slug`) is ordinary admin
     * configuration. An update that changes the key column must read the
     * row back by its new key and report the new key, not the one it no
     * longer has.
     */
    #[DataProvider('connections')]
    public function testAnUpdateThatChangesTheKeyColumnIsReadBackByTheNewKey(?Connection $connection): void
    {
        $connection = $this->requireConnection($connection);
        $handler = $this->handler($connection);
        $entity = $this->entity();

        $handler->insert($entity, ['id' => 1, 'title' => 'Horské kolo', 'price' => 12000]);

        $result = $handler->update($entity, '1', ['id' => 2, 'title' => 'Nové jméno']);

        $this->assertSame('2', $result->key);
        $this->assertSame(1, $this->intValue($result->before['id']));
        $this->assertSame(2, $this->intValue($result->after['id']));
        $this->assertArrayHasKey('id', $result->changed(), 'the key column itself changed');

        $rows = $connection->select(new Sql('SELECT id, title FROM ra_test_write'));

        $this->assertCount(1, $rows, 'the row was renamed, not duplicated');
        $this->assertSame(2, $this->intValue($rows[0]['id']));
        $this->assertSame('Nové jméno', $rows[0]['title']);
    }

    #[DataProvider('connections')]
    public function testADeleteRemovesTheRow(?Connection $connection): void
    {
        $connection = $this->requireConnection($connection);
        $handler = $this->handler($connection);
        $entity = $this->entity();

        $handler->insert($entity, ['id' => 1, 'title' => 'Horské kolo', 'price' => 12000]);
        $handler->delete($entity, '1');

        $rows = $connection->select(new Sql('SELECT id FROM ra_test_write WHERE id = ?', [1]));

        $this->assertSame([], $rows);
    }

    #[DataProvider('connections')]
    public function testADeleteReturnsTheRowThatWasThere(?Connection $connection): void
    {
        $connection = $this->requireConnection($connection);
        $handler = $this->handler($connection);
        $entity = $this->entity();

        $handler->insert($entity, ['id' => 1, 'title' => 'Horské kolo', 'price' => 12000]);
        $result = $handler->delete($entity, '1');

        $this->assertSame([], $result->after);
        $this->assertSame('Horské kolo', $result->before['title']);
    }

    #[DataProvider('connections')]
    public function testATransactionRollsBackEverythingWhenTheWorkThrows(?Connection $connection): void
    {
        $connection = $this->requireConnection($connection);

        $this->expectException(RuntimeException::class);
        $this->expectExceptionMessage('Something went wrong before the second row.');

        try {
            $connection->transaction(static function () use ($connection): void {
                $connection->execute(new Sql(
                    'INSERT INTO ra_test_write (id, title, price) VALUES (?, ?, ?)',
                    [1, 'First', 100],
                ));

                // The second row is never even attempted -- what matters is
                // that the first one, already sent, does not survive either.
                throw new RuntimeException('Something went wrong before the second row.');
            });
        } finally {
            $rows = $connection->select(new Sql('SELECT id FROM ra_test_write'));

            $this->assertSame([], $rows, 'neither row survives the rollback');
        }
    }

    /**
     * I3: nesting joins the transaction this connection already has open,
     * rather than being refused -- what lets a bulk action open one
     * transaction around a loop of writes that each open their own. Both
     * inserts commit together, as one transaction, when neither throws.
     */
    #[DataProvider('connections')]
    public function testTwoNestedTransactionsCommitTogetherAsOne(?Connection $connection): void
    {
        $connection = $this->requireConnection($connection);
        $handler = $this->handler($connection);
        $entity = $this->entity();

        $connection->transaction(function () use ($handler, $entity): void {
            $handler->insert($entity, ['id' => 1, 'title' => 'First', 'price' => 100]);
            $handler->insert($entity, ['id' => 2, 'title' => 'Second', 'price' => 200]);
        });

        $rows = $connection->select(new Sql('SELECT id FROM ra_test_write'));

        $this->assertCount(2, $rows, 'both writes, each opening its own transaction(), must commit');
    }

    /**
     * A nested transaction still shares the outer one's fate: the inner
     * write is not committed just because it is not the one that threw.
     */
    #[DataProvider('connections')]
    public function testANestedTransactionRollsBackTogetherWithTheOuterOneWhenEitherThrows(
        ?Connection $connection,
    ): void {
        $connection = $this->requireConnection($connection);

        $this->expectException(RuntimeException::class);
        $this->expectExceptionMessage('Inner write failed.');

        try {
            $connection->transaction(static function () use ($connection): void {
                $connection->execute(new Sql(
                    'INSERT INTO ra_test_write (id, title, price) VALUES (?, ?, ?)',
                    [1, 'Outer', 100],
                ));

                $connection->transaction(static function () use ($connection): void {
                    $connection->execute(new Sql(
                        'INSERT INTO ra_test_write (id, title, price) VALUES (?, ?, ?)',
                        [2, 'Inner', 200],
                    ));

                    throw new RuntimeException('Inner write failed.');
                });
            });
        } finally {
            $rows = $connection->select(new Sql('SELECT id FROM ra_test_write'));

            $this->assertSame([], $rows, 'the outer write must roll back along with the inner one');
        }
    }

    /**
     * The refusal that remains: a transaction this connection did not open
     * itself, which `transaction()` has no way to safely commit or roll
     * back on the caller's behalf.
     */
    #[DataProvider('connections')]
    public function testAForeignTransactionIsRefusedRatherThanJoined(?Connection $connection): void
    {
        $connection = $this->requireConnection($connection);

        $begin = $connection->dialect()->name() === 'mysql' ? 'START TRANSACTION' : 'BEGIN';
        $connection->execute(new Sql($begin));

        $this->expectException(DbException::class);

        try {
            $connection->transaction(static fn (): null => null);
        } finally {
            // Leaves the connection as this test found it, for whichever test
            // runs next against the same cached connection.
            $connection->execute(new Sql('ROLLBACK'));
        }
    }

    #[DataProvider('connections')]
    public function testAUniqueViolationPropagatesWithItsSqlState(?Connection $connection): void
    {
        $connection = $this->requireConnection($connection);
        $handler = $this->handler($connection);
        $entity = $this->entity();

        $handler->insert($entity, ['id' => 1, 'title' => 'Horské kolo', 'price' => 12000]);

        try {
            $handler->insert($entity, ['id' => 2, 'title' => 'Horské kolo', 'price' => 25000]);

            $this->fail('Expected the duplicate title to raise a DbException.');
        } catch (DbException $e) {
            $this->assertSame('23', $e->sqlStateClass(), 'class 23 is an integrity constraint violation');
        }

        $rows = $connection->select(new Sql('SELECT id FROM ra_test_write'));

        $this->assertCount(1, $rows, 'the failed second insert must not have left anything behind');
    }

    /**
     * I5: without a strict MySQL `sql_mode`, `WHERE id = '4abc'` used to
     * coerce silently to `WHERE id = 4` and delete the wrong row -- the
     * SELECT this test's own `find()` step runs still does (confirmed
     * below), but the DELETE statement itself now refuses under
     * `STRICT_TRANS_TABLES`, which `DatabaseTestCase::connect()` sets for
     * every MySQL session. PostgreSQL refuses it unconditionally either
     * way. Row 4 must survive on both.
     */
    #[DataProvider('connections')]
    public function testADeleteWithAKeyThatDoesNotFitTheColumnsTypeDoesNotDeleteTheWrongRow(
        ?Connection $connection,
    ): void {
        $connection = $this->requireConnection($connection);
        $handler = $this->handler($connection);
        $entity = $this->entity();

        $handler->insert($entity, ['id' => 4, 'title' => 'Row four', 'price' => 100]);

        try {
            $handler->delete($entity, '4abc');

            $this->fail('Expected a malformed key to be refused rather than silently matching row 4.');
        } catch (DbException $e) {
            $this->assertStringContainsString('4abc', $e->getMessage());
        }

        $rows = $connection->select(new Sql('SELECT id FROM ra_test_write WHERE id = ?', [4]));

        $this->assertCount(1, $rows, 'row 4 must survive a malformed key');
    }
}
