<?php

declare(strict_types=1);

namespace RockAdmin\Config;

/**
 * The compiled configuration: one include, sitting in opcache.
 *
 * In production this replaces reading a directory of files and validating
 * every key on every request. Placeholder, EnumReference and EnumOption
 * survive the round trip through __set_state(); a closure cannot, which is the
 * reason configuration holds data and the host supplies services.
 */
final class Cache
{
    public function __construct(private readonly string $file)
    {
    }

    public function read(): ?Config
    {
        if (!is_file($this->file)) {
            return null;
        }

        $restored = require $this->file;

        if (!$restored instanceof Config) {
            throw new ConfigException(
                "{$this->file} is not a compiled configuration. Delete it and build it again.",
            );
        }

        return $restored;
    }

    public function write(Config $config): void
    {
        $this->assertExportable($config->all(), '');

        $source = \sprintf(
            "<?php\n\n// Generated by RockAdmin. Do not edit; rebuild it instead.\n\ndeclare(strict_types=1);\n\nreturn %s;\n",
            var_export($config, true),
        );

        $directory = \dirname($this->file);

        if (!is_dir($directory) && !mkdir($directory, 0o775, true) && !is_dir($directory)) {
            throw new ConfigException("Cannot create the cache directory: {$directory}");
        }

        $temporary = $this->file . '.' . bin2hex(random_bytes(6)) . '.tmp';

        $written = file_put_contents($temporary, $source, LOCK_EX);

        // A short write -- a full disk -- returns a byte count, not false. Renaming
        // a truncated file into place would make every request fatal on a parse
        // error, which is the failure the atomic rename exists to prevent.
        if ($written !== \strlen($source)) {
            @unlink($temporary);

            throw new ConfigException("Cannot write the configuration cache: {$temporary}");
        }

        // The compiled cache can hold resolved {{env.*}} values, which is to say
        // secrets, so it is not left at whatever the umask allows.
        chmod($temporary, 0o600);

        // Renaming within a directory is atomic, so a request served during a deploy
        // includes either the whole old file or the whole new one. Writing in place
        // would let it include a half-written one, and `require` ignores the lock.
        if (!rename($temporary, $this->file)) {
            @unlink($temporary);

            throw new ConfigException("Cannot replace the configuration cache: {$this->file}");
        }
    }

    public function clear(): void
    {
        if (is_file($this->file)) {
            unlink($this->file);
        }
    }

    /**
     * Refuses anything var_export() cannot round-trip, naming where it is.
     *
     * Without this the failure would be an unreadable generated file at the
     * next request, rather than a message pointing at the offending key.
     *
     * @param array<array-key, mixed> $value
     */
    private function assertExportable(array $value, string $prefix): void
    {
        foreach ($value as $name => $entry) {
            $path = $prefix === '' ? (string) $name : "{$prefix}.{$name}";

            if (\is_array($entry)) {
                $this->assertExportable($entry, $path);

                continue;
            }

            if ($entry === null || \is_scalar($entry)) {
                continue;
            }

            if (\is_object($entry) && method_exists($entry, '__set_state')) {
                continue;
            }

            throw new ConfigException(\sprintf(
                "Configuration value at '%s' is a %s, which cannot be cached. "
                . 'Configuration holds data; services such as a connection, a '
                . 'mailer or a callback are given to the bootstrap instead.',
                $path,
                get_debug_type($entry),
            ));
        }
    }
}
