<?php

declare(strict_types=1);

/**
 * Creates and fills the fixture tables the demo's `ads` page reads from.
 *
 * Same tables, same driver detection as `tests/Support/DatabaseTestCase.php`
 * — `ra_test_companies`, `ra_test_users`, `ra_test_ads` and `ra_test_tags` —
 * with four columns on `ra_test_ads` that a unit test does not need but this
 * page's worked example does: `created_at` for the sortable date column and
 * the form's hidden `@now` field, `description` for a textarea, `featured` for
 * a checkbox and `published_on` for a date field. Running the test suite
 * afterwards is still safe: `DatabaseTestCase::createFixtures()` drops and
 * recreates every one of these tables before each test that needs them, so it
 * never sees this script's extra columns or its extra rows.
 *
 * `ra_test_ads.id` is a generated key — `AUTO_INCREMENT` on MySQL,
 * `GENERATED BY DEFAULT AS IDENTITY` on PostgreSQL — because the form on that
 * page creates rows and nothing in a create form supplies a primary key. The
 * seed rows below still name their own ids, so the tags can point at them, and
 * the identity is then restarted past the last of them: a PostgreSQL identity
 * column does not notice an explicitly inserted value, so without the restart
 * the first row created through the form would collide with ad 1.
 *
 * Run it once, against whichever server is configured:
 *
 *     php demo/seed.php
 *
 * It reads the same `RA_TEST_MYSQL_*` / `RA_TEST_PGSQL_*` variables the test
 * suite does, seeds every server it finds configured, and says plainly when
 * it finds none — the same honesty `demo/index.php` shows on the page itself
 * when nothing is configured.
 */

require __DIR__ . '/../vendor/autoload.php';

use RockAdmin\Db\Connection;
use RockAdmin\Db\Sql;

/** @return array{dsn: string, user: ?string, password: ?string}|null */
function seedServerConfig(string $prefix): ?array
{
    $dsn = getenv("RA_TEST_{$prefix}_DSN");

    if (!is_string($dsn) || $dsn === '') {
        return null;
    }

    $user = getenv("RA_TEST_{$prefix}_USER");
    $password = getenv("RA_TEST_{$prefix}_PASSWORD");

    return [
        'dsn' => $dsn,
        'user' => is_string($user) ? $user : null,
        'password' => is_string($password) ? $password : null,
    ];
}

/** @param array{dsn: string, user: ?string, password: ?string} $server */
function seedOneServer(string $label, array $server): void
{
    $pdo = new PDO($server['dsn'], $server['user'], $server['password']);
    $connection = Connection::fromPdo($pdo);
    $mysql = $connection->dialect()->name() === 'mysql';
    $json = $mysql ? 'JSON' : 'JSONB';
    $key = $mysql
        ? 'INTEGER AUTO_INCREMENT PRIMARY KEY'
        : 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
    $boolean = $mysql ? 'TINYINT(1)' : 'BOOLEAN';
    $false = $mysql ? '0' : 'FALSE';

    foreach (['ra_test_tags', 'ra_test_ads', 'ra_test_users', 'ra_test_companies'] as $table) {
        $connection->execute(new Sql("DROP TABLE IF EXISTS {$table}"));
    }

    foreach ([
        'CREATE TABLE ra_test_companies (id INTEGER PRIMARY KEY, name VARCHAR(100) NOT NULL)',
        'CREATE TABLE ra_test_users (id INTEGER PRIMARY KEY, company_id INTEGER, '
            . 'name VARCHAR(100) NOT NULL, email VARCHAR(100))',
        "CREATE TABLE ra_test_ads (id {$key}, user_id INTEGER, "
            . 'title VARCHAR(200) NOT NULL, description TEXT, price INTEGER, state VARCHAR(20), '
            . "featured {$boolean} NOT NULL DEFAULT {$false}, published_on DATE, stats {$json}, "
            . 'created_at TIMESTAMP)',
        'CREATE TABLE ra_test_tags (id INTEGER PRIMARY KEY, ad_id INTEGER, label VARCHAR(50))',
    ] as $ddl) {
        $connection->execute(new Sql($ddl));
    }

    foreach ([
        ['INSERT INTO ra_test_companies (id, name) VALUES (?, ?)', [1, 'Velo s.r.o.']],
        ['INSERT INTO ra_test_companies (id, name) VALUES (?, ?)', [2, 'Moto a.s.']],
        ['INSERT INTO ra_test_users (id, company_id, name, email) VALUES (?, ?, ?, ?)',
            [1, 1, 'Jana', 'jana@example.com']],
        ['INSERT INTO ra_test_users (id, company_id, name, email) VALUES (?, ?, ?, ?)',
            [2, 2, 'Petr', 'petr@example.com']],
    ] as [$text, $bindings]) {
        $connection->execute(new Sql($text, $bindings));
    }

    $states = ['active', 'active', 'draft', 'active', 'sold'];
    $titles = [
        'Horské kolo', 'Silniční kolo', 'Skútr', 'Elektrokolo', 'Koloběžka',
        'Dětské kolo', 'Trekové kolo', 'BMX', 'Motorka Honda', 'Přívěsný vozík',
        'Cyklopočítač', 'Helma Giro',
    ];

    $adId = 1;
    $tagId = 1;

    foreach ($titles as $index => $title) {
        $userId = $index % 2 === 0 ? 1 : 2;
        $price = 5000 + $index * 1750;
        $state = $states[$index % count($states)];
        $stats = json_encode(['daily' => ['views' => 3 + $index * 7]], JSON_THROW_ON_ERROR);
        $createdAt = (new DateTimeImmutable('-' . $index . ' days'))->format('Y-m-d H:i:s');
        $publishedOn = $state === 'draft'
            ? null
            : (new DateTimeImmutable('-' . $index . ' days'))->format('Y-m-d');

        $connection->execute(new Sql(
            'INSERT INTO ra_test_ads (id, user_id, title, description, price, state, featured, '
                . 'published_on, stats, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
            [
                $adId,
                $userId,
                $title,
                "{$title} \u{2014} popis inzerátu, seeded so the textarea has something to draw.",
                $price,
                $state,
                $index % 4 === 0,
                $publishedOn,
                $stats,
                $createdAt,
            ],
        ));

        foreach (array_slice(['bazar', 'sleva', 'novinka', 'doprava-zdarma'], 0, $index % 3) as $tagLabel) {
            $connection->execute(new Sql(
                'INSERT INTO ra_test_tags (id, ad_id, label) VALUES (?, ?, ?)',
                [$tagId++, $adId, $tagLabel],
            ));
        }

        $adId++;
    }

    // The rows above named their own ids, which a PostgreSQL identity column
    // does not notice: its sequence is still at 1, so the first ad created
    // through the demo's form would collide with ad 1. MySQL advances
    // AUTO_INCREMENT past an explicit value on its own, but is restarted here
    // too so both servers hand out the same next key.
    $connection->execute(new Sql($mysql
        ? 'ALTER TABLE ra_test_ads AUTO_INCREMENT = ' . $adId
        : 'ALTER TABLE ra_test_ads ALTER COLUMN id RESTART WITH ' . $adId));

    echo "Seeded {$label}: " . count($titles) . " ads.\n";
}

$found = false;

foreach (['mysql' => 'MYSQL', 'pgsql' => 'PGSQL'] as $label => $prefix) {
    $server = seedServerConfig($prefix);

    if ($server !== null) {
        $found = true;
        seedOneServer($label, $server);
    }
}

if (!$found) {
    echo 'No database configured. Set RA_TEST_MYSQL_DSN (and, optionally, RA_TEST_PGSQL_DSN) '
        . "before running this script -- the same variables the test suite reads.\n";
    exit(1);
}
